# Generated by Django 4.2.5 on 2023-12-05 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('title', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'flashcard',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='SharedFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.flashcard')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.group')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('content', models.CharField(default='Empty Note', max_length=500)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.accounts')),
            ],
            options={
                'db_table': 'notes',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='flashcards',
            field=models.ManyToManyField(through='pages.SharedFlashcard', to='pages.flashcard'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_members',
            field=models.ManyToManyField(to='pages.accounts'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='groups',
            field=models.ManyToManyField(through='pages.SharedFlashcard', to='pages.group'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.accounts'),
        ),
        migrations.CreateModel(
            name='CreateFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flashcard_identifier', models.CharField(max_length=50)),
                ('difinition', models.CharField(max_length=500)),
                ('term', models.CharField(max_length=500)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.flashcard')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.accounts')),
            ],
            options={
                'db_table': 'createflashcard',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.group')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.accounts')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ('timestamp',),
            },
        ),
    ]
