# Generated by Django 4.2.5 on 2023-12-06 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_compilersubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.group')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.notes')),
            ],
            options={
                'db_table': 'shared_notes',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='notes',
            field=models.ManyToManyField(through='pages.SharedNote', to='pages.notes'),
        ),
    ]
