# Generated by Django 4.2.5 on 2023-12-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_sharednote_group_notes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sharednote',
            table=None,
        ),
    ]
